name: sweph
description: Cross-platform bindings of Swiss Ephemeris APIs for Flutter.
version: 3.2.0+2.10.3
homepage: https://github.com/vm75/sweph.dart
repository: https://github.com/vm75/sweph.dart
publish_to: none

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  path: ^1.9.0
  universal_ffi: ^1.1.0

dependency_overrides:
  wasm_ffi:
    git:
      url: https://github.com/dh0er/wasm_ffi.git

dev_dependencies:
  ffigen: ^14.0.0
  lints: ^4.0.0
  test: ^1.24.0

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
      web:
        pluginClass: Sweph
        fileName: sweph.dart
  assets:
    - assets/
    - assets/ephe/
